version: '3.8'

services:
  brickMongoDB:
    image: mongodb/mongodb-community-server:8.0.9-ubi9
    container_name: brickMongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: labtelematica
      MONGO_INITDB_ROOT_PASSWORD: l4bt3l3m4tic@
    networks:
      - brickNetwork
    restart: unless-stopped
    tty: true
    stdin_open: true

  node-red:
    image: nodered/node-red:latest
    container_name: brickNode-Red
    ports:
      - "1880:1880"
    volumes:
      - node-red_data:/data
    networks:
      - brickNetwork
    environment:
      - name=value
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  mongodb_data:
  mongodb_config:
  node-red_data:

networks:
  brickNetwork:
    external: true
