version: '3.8'

services:
  brickMongoDB:
    image: mongodb/mongodb-community-server:8.0.9-ubi9
    container_name: brickMongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:?set it in Services/.env}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:?set it in Services/.env}
    networks:
      - brickNetwork
    restart: unless-stopped
    tty: true
    stdin_open: true

  node-red:
    image: nodered/node-red:latest
    container_name: brickNode-Red
    ports:
      - "1880:1880"
    volumes:
      - node-red_data:/data
    networks:
      - brickNetwork
    environment:
      - NODERED_ADMIN_USER=${NODERED_ADMIN_USER:?set it in Services/.env}
      - NODERED_ADMIN_PASSWORD_HASH=${NODERED_ADMIN_PASSWORD_HASH:?set it in Services/.env}
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  mongodb_data:
  mongodb_config:
  node-red_data:

networks:
  brickNetwork:
    external: true
